<?xml version="1.0" encoding = "Windows-1252"?>
<VisualStudioProject
	ProjectType="Visual C++"
	Version="8.00"
	Name="ga"
	ProjectGUID="{F1863A93-A6E4-4709-B061-6BF53F138670}"
	SccProjectName=""
	SccLocalPath=""
	Keyword="Win32Proj">
	<Platforms>
		<Platform
			Name="Win32"/>
	</Platforms>
	<Configurations>
		<Configuration
			Name="Debug|Win32"
			OutputDirectory="Debug"
			IntermediateDirectory="ga.dir\Debug"
			ConfigurationType="4"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions=" CreateProcessError: The system cannot find the file specified. for command: freetype-config --cflags"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				BasicRuntimeChecks="3"
				CompileAs="2"
				DebugInformationFormat="3"
				ExceptionHandling="FALSE"
				InlineFunctionExpansion="0"
				Optimization="0"
				RuntimeLibrary="3"
				PreprocessorDefinitions="_DEBUG,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"
				AssemblerListingLocation="Debug"
				ObjectFile="$(IntDir)\"
				ProgramDataBaseFileName="T:/dev\build\Windows-x86\lib/Debug/ga.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				PreprocessorDefinitions="_DEBUG,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="_DEBUG,&quot;CMAKE_INTDIR=\&quot;Debug\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCManifestTool"
				UseFAT32Workaround="true"
			/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="T:\dev\build\Windows-x86\lib\$(OutDir)\ga.lib"/>
		</Configuration>
		<Configuration
			Name="Release|Win32"
			OutputDirectory="Release"
			IntermediateDirectory="ga.dir\Release"
			ConfigurationType="4"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions=" CreateProcessError: The system cannot find the file specified. for command: freetype-config --cflags"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				CompileAs="2"
				ExceptionHandling="FALSE"
				InlineFunctionExpansion="2"
				Optimization="2"
				RuntimeLibrary="2"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"
				AssemblerListingLocation="Release"
				ObjectFile="$(IntDir)\"
				ProgramDataBaseFileName="T:/dev\build\Windows-x86\lib/Release/ga.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;Release\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCManifestTool"
				UseFAT32Workaround="true"
			/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="T:\dev\build\Windows-x86\lib\$(OutDir)\ga.lib"/>
		</Configuration>
		<Configuration
			Name="MinSizeRel|Win32"
			OutputDirectory="MinSizeRel"
			IntermediateDirectory="ga.dir\MinSizeRel"
			ConfigurationType="4"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions=" CreateProcessError: The system cannot find the file specified. for command: freetype-config --cflags"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				CompileAs="2"
				ExceptionHandling="FALSE"
				InlineFunctionExpansion="1"
				Optimization="1"
				RuntimeLibrary="2"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;MinSizeRel\&quot;&quot;"
				AssemblerListingLocation="MinSizeRel"
				ObjectFile="$(IntDir)\"
				ProgramDataBaseFileName="T:/dev\build\Windows-x86\lib/MinSizeRel/ga.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;MinSizeRel\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;MinSizeRel\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCManifestTool"
				UseFAT32Workaround="true"
			/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="T:\dev\build\Windows-x86\lib\$(OutDir)\ga.lib"/>
		</Configuration>
		<Configuration
			Name="RelWithDebInfo|Win32"
			OutputDirectory="RelWithDebInfo"
			IntermediateDirectory="ga.dir\RelWithDebInfo"
			ConfigurationType="4"
			UseOfMFC="0"
			ATLMinimizesCRunTimeLibraryUsage="FALSE"
			CharacterSet="2">
			<Tool
				Name="VCCLCompilerTool"
				AdditionalOptions=" CreateProcessError: The system cannot find the file specified. for command: freetype-config --cflags"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				CompileAs="2"
				DebugInformationFormat="3"
				ExceptionHandling="FALSE"
				InlineFunctionExpansion="1"
				Optimization="2"
				RuntimeLibrary="2"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;&quot;"
				AssemblerListingLocation="RelWithDebInfo"
				ObjectFile="$(IntDir)\"
				ProgramDataBaseFileName="T:/dev\build\Windows-x86\lib/RelWithDebInfo/ga.pdb"
/>
			<Tool
				Name="VCCustomBuildTool"/>
			<Tool
				Name="VCResourceCompilerTool"
				AdditionalIncludeDirectories="T:\dev\src;\include;"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;&quot;"/>
			<Tool
				Name="VCMIDLTool"
				PreprocessorDefinitions="NDEBUG,&quot;CMAKE_INTDIR=\&quot;RelWithDebInfo\&quot;&quot;"
				MkTypLibCompatible="FALSE"
				TargetEnvironment="1"
				GenerateStublessProxies="TRUE"
				TypeLibraryName="$(InputName).tlb"
				OutputDirectory="$(IntDir)"
				HeaderFileName="$(InputName).h"
				DLLDataFileName=""
				InterfaceIdentifierFileName="$(InputName)_i.c"
				ProxyFileName="$(InputName)_p.c"/>
			<Tool
				Name="VCManifestTool"
				UseFAT32Workaround="true"
			/>
			<Tool
				Name="VCPreBuildEventTool"/>
			<Tool
				Name="VCPreLinkEventTool"/>
			<Tool
				Name="VCPostBuildEventTool"/>
			<Tool
				Name="VCLibrarianTool"
				OutputFile="T:\dev\build\Windows-x86\lib\$(OutDir)\ga.lib"/>
		</Configuration>
	</Configurations>
	<Files>
			<File
				RelativePath="T:\dev\src\ga\CMakeLists.txt">
				<FileConfiguration
					Name="Debug|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule T:/dev/src/ga/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HT:/dev -BT:/dev"
					AdditionalDependencies="T:\dev\src\ga\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;T:\dev\src\ga\CMakeLists.txt;"
					Outputs="ga.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="Release|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule T:/dev/src/ga/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HT:/dev -BT:/dev"
					AdditionalDependencies="T:\dev\src\ga\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;T:\dev\src\ga\CMakeLists.txt;"
					Outputs="ga.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="MinSizeRel|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule T:/dev/src/ga/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HT:/dev -BT:/dev"
					AdditionalDependencies="T:\dev\src\ga\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;T:\dev\src\ga\CMakeLists.txt;"
					Outputs="ga.vcproj.cmake"/>
				</FileConfiguration>
				<FileConfiguration
					Name="RelWithDebInfo|Win32">
					<Tool
					Name="VCCustomBuildTool"
					Description="Building Custom Rule T:/dev/src/ga/CMakeLists.txt"
					CommandLine="&quot;C:\Program Files\CMake 2.4\bin\cmake.exe&quot; -HT:/dev -BT:/dev"
					AdditionalDependencies="T:\dev\src\ga\CMakeLists.txt;&quot;C:\Program Files\CMake 2.4\share\cmake-2.4\Templates\CMakeWindowsSystemConfig.cmake&quot;;T:\dev\src\ga\CMakeLists.txt;"
					Outputs="ga.vcproj.cmake"/>
				</FileConfiguration>
			</File>
		<Filter
			Name="Source Files"
			Filter="">
			<File
				RelativePath="T:\dev\src\ga\garandom.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\gaerror.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAParameter.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAStatistics.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GABaseGA.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GASStateGA.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GASimpleGA.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAIncGA.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GADemeGA.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GADCrowdingGA.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GASelector.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAScaling.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAPopulation.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GABinStr.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\gabincvt.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAAllele.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAStringGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GARealGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GA1DBinStrGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GA2DBinStrGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GA3DBinStrGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GABin2DecGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GA1DArrayGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GA2DArrayGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GA3DArrayGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GATreeBASE.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GATree.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GATreeGenome.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAListBASE.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAList.C">
			</File>
			<File
				RelativePath="T:\dev\src\ga\GAListGenome.C">
			</File>
		</Filter>
	</Files>
	<Globals>
	</Globals>
</VisualStudioProject>
