/////////////////////////////////////////////////////////////////////////////
// Name:        mainframe.h
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Wed 05 Dec 2007 02:12:05 PM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Wed 05 Dec 2007 02:12:05 PM CST

#ifndef _MAINFRAME_H_
#define _MAINFRAME_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "mainframe.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/frame.h"
#include "wx/notebook.h"
#include "wx/statusbr.h"
////@end includes


#include "appinterface.h"
#include "wxpagegeneralsettings.h"
#include "wximggrowthchart.h"
#include "wxldanalysis.h"
#include "wxpagelocicreation.h"
#include "wxpagelocusreporting.h"
#include "wxpanelreports.h"
#include "modellist.h"
/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations
#include "locusmanager.h"
/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_GENOMESIMLA_MAINFRAME 10030
#define ID_NB_MAINCFG 10031
#define ID_MENU_OPEN_RECENT 10053
#define ID_STATUSBAR1 10057
#define SYMBOL_MAINFRAME_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxMAXIMIZE_BOX
//|wxCLOSE_BOX
#define SYMBOL_MAINFRAME_TITLE _("genomeSIMLA")
#define SYMBOL_MAINFRAME_IDNAME ID_GENOMESIMLA_MAINFRAME
#define SYMBOL_MAINFRAME_SIZE wxSize(800, 600)
#define SYMBOL_MAINFRAME_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif


namespace GenomeSIM {

namespace GUI {


/*!
 * MainFrame class declaration
 */

class MainFrame: public wxFrame, public AppInterface {    
    DECLARE_CLASS( MainFrame )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    MainFrame( );
    MainFrame( wxWindow* parent, wxWindowID id = SYMBOL_MAINFRAME_IDNAME, const wxString& caption = SYMBOL_MAINFRAME_TITLE, const wxPoint& pos = SYMBOL_MAINFRAME_POSITION, const wxSize& size = SYMBOL_MAINFRAME_SIZE, long style = SYMBOL_MAINFRAME_STYLE );

	~MainFrame();

    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_MAINFRAME_IDNAME, const wxString& caption = SYMBOL_MAINFRAME_TITLE, const wxPoint& pos = SYMBOL_MAINFRAME_POSITION, const wxSize& size = SYMBOL_MAINFRAME_SIZE, long style = SYMBOL_MAINFRAME_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin MainFrame event handler declarations

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_NEW
    void OnNewClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_OPEN
    void OnOpenClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_SAVE
    void OnSaveClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_SAVEAS
    void OnSaveAsClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_RESET
    void OnResetClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for wxID_EXIT
    void OnExitClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_LAUNCH
    void OnMenuLaunchClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_DETAILED_ANALYSIS
    void OnMenuDetailedAnalysisClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_MENU_EXTRACT_DATASETS_GEN_0
    void OnMenuExtractDatasetsGen0Click( wxCommandEvent& event );

////@end MainFrame event handler declarations
	void OnAbout(wxCommandEvent& event);

////@begin MainFrame member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end MainFrame member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin MainFrame member variables
////@end MainFrame member variables

	wxLdAnalysis			*pageLdAnalysis;
	wxPageLociCreation 		*pageLociCreation;
	wxPageLocusReporting 	*pageLocusReport;
	wxPageGeneralSettings	*pageGeneralSettings;
	wxPanelReports 			*pReporting;
//	wxPanelSimulationReports *pReports;
	wxStatusBar 		 	*statusBar;
	void InitAppController(AppController *);

	/**
	 * @brief This is called prior to saving the configuration
	 */
	void Commit();

	/**
	 * @brief This is called just after a configuration has been loaded
	 */
	void RefreshSettings();

	bool HasChanged();
	
	void OnContinueSimulation(wxCommandEvent& event);
	void OnDetailedAnalysis(wxCommandEvent& event);
	void OpenReport(wxCommandEvent& event);
	void ExtractData(wxCommandEvent& event);

	bool VerifyForRun();

	/**
	 * @brief check to see if changes have been made and prompt for changes
	 * @Notes if changes have been made but the user chooses no, return false. Otherwise, return yes
	 */
	bool PromptForChanges();
protected:
	
	vector<FileBasedChromosome *> fileBasedChromosomes;
	ModelList *modelList;				///<Library for disease models
	void SaveAs();
	void Save();
};
}

}



#endif
    // _MAINFRAME_H_
