/////////////////////////////////////////////////////////////////////////////
// Name:        wxldanalysis.h
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Wed 05 Dec 2007 02:48:35 PM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Wed 05 Dec 2007 02:48:35 PM CST

#ifndef _WXLDANALYSIS_H_
#define _WXLDANALYSIS_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "wxldanalysis.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_PAGE_LD_ANALYSIS 10037
#define ID_TXT_MAX_SNP_DIST 10007
#define ID_TXT_REPORT_BUFFER_SIZE 10002
#define ID_TXT_TARGET_POP_SIZE 10009
#define ID_CHK_WRITE_PAIRWISE_LD 10003
#define ID_CHK_PLOT_R 10004
#define ID_CHK_PLOT_DPRIME 10005
#define ID_CHK_FAST_LD 10051
#define ID_TXT_REPORT_STYLE_SHEET 10001
#define ID_SELECT_STYLE_SHEET 10006
#define ID_TXT_FONT_NAME 10000
#define ID_CMD_SELECT_FONT 10008
#define SYMBOL_WXLDANALYSIS_STYLE 0
#define SYMBOL_WXLDANALYSIS_TITLE _("LD Analysis")
#define SYMBOL_WXLDANALYSIS_IDNAME ID_PAGE_LD_ANALYSIS
#define SYMBOL_WXLDANALYSIS_SIZE wxSize(400, 300)
#define SYMBOL_WXLDANALYSIS_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif


#include "appinterface.h"

namespace GenomeSIM {

namespace GUI {
/*!
 * wxLdAnalysis class declaration
 */

class wxLdAnalysis: public wxPanel, public AppInterface 	{    
    DECLARE_DYNAMIC_CLASS( wxLdAnalysis )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxLdAnalysis( );
    wxLdAnalysis( wxWindow* parent, wxWindowID id = SYMBOL_WXLDANALYSIS_IDNAME, const wxPoint& pos = SYMBOL_WXLDANALYSIS_POSITION, const wxSize& size = SYMBOL_WXLDANALYSIS_SIZE, long style = SYMBOL_WXLDANALYSIS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXLDANALYSIS_IDNAME, const wxPoint& pos = SYMBOL_WXLDANALYSIS_POSITION, const wxSize& size = SYMBOL_WXLDANALYSIS_SIZE, long style = SYMBOL_WXLDANALYSIS_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxLdAnalysis event handler declarations

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TXT_MAX_SNP_DIST
    void OnTxtMaxSnpDistEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TXT_REPORT_BUFFER_SIZE
    void OnTxtReportBufferSizeEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TXT_TARGET_POP_SIZE
    void OnTxtTargetPopSizeEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHK_WRITE_PAIRWISE_LD
    void OnChkWritePairwiseLdClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHK_PLOT_R
    void OnChkPlotRClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_CHECKBOX_CLICKED event handler for ID_CHK_PLOT_DPRIME
    void OnChkPlotDprimeClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TXT_REPORT_STYLE_SHEET
    void OnTxtReportStyleSheetEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_SELECT_STYLE_SHEET
    void OnSelectStyleSheetClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_TEXT_ENTER event handler for ID_TXT_FONT_NAME
    void OnTxtFontNameEnter( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for ID_CMD_SELECT_FONT
    void OnCmdSelectFontClick( wxCommandEvent& event );

////@end wxLdAnalysis event handler declarations

////@begin wxLdAnalysis member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxLdAnalysis member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxLdAnalysis member variables
    wxTextCtrl* txtMaxSnpDist;
    wxTextCtrl* txtReportBufferSize;
    wxTextCtrl* txtTargetPopulation;
    wxCheckBox* chkWritePairwiseLD;
    wxCheckBox* chkPlotRSquared;
    wxCheckBox* chkPlotDPrime;
    wxCheckBox* chkFastLD;
    wxTextCtrl* txtStyleSheetFilename;
    wxTextCtrl* txtFontFilename;
////@end wxLdAnalysis member variables

	void InitAppController(AppController *);

	/**
	 * @brief This is called prior to saving the configuration
	 */
	void Commit();

	/**
	 * @brief This is called just after a configuration has been loaded
	 */
	void RefreshSettings();

	bool HasChanged();

	bool VerifyForRun();

protected:
	bool hasChanged;
};

}

}

#endif
    // _WXLDANALYSIS_H_
