/////////////////////////////////////////////////////////////////////////////
// Name:        wxpageinfo.h
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Thu 06 Dec 2007 09:38:49 AM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Thu 06 Dec 2007 09:38:49 AM CST

#ifndef _WXPAGEINFO_H_
#define _WXPAGEINFO_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "wxpageinfo.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_MYDIALOG 10048
#define SYMBOL_WXPAGEINFO_STYLE 0
#define SYMBOL_WXPAGEINFO_TITLE _("Message Panel")
#define SYMBOL_WXPAGEINFO_IDNAME ID_MYDIALOG
#define SYMBOL_WXPAGEINFO_SIZE wxSize(400, 300)
#define SYMBOL_WXPAGEINFO_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif


namespace GenomeSIM {

namespace GUI {

/*!
 * wxPageInfo class declaration
 */

class wxPageInfo: public wxPanel
{    
    DECLARE_DYNAMIC_CLASS( wxPageInfo )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxPageInfo( );
    wxPageInfo( wxWindow* parent, wxWindowID id = SYMBOL_WXPAGEINFO_IDNAME, const wxPoint& pos = SYMBOL_WXPAGEINFO_POSITION, const wxSize& size = SYMBOL_WXPAGEINFO_SIZE, long style = SYMBOL_WXPAGEINFO_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXPAGEINFO_IDNAME, const wxPoint& pos = SYMBOL_WXPAGEINFO_POSITION, const wxSize& size = SYMBOL_WXPAGEINFO_SIZE, long style = SYMBOL_WXPAGEINFO_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxPageInfo event handler declarations

////@end wxPageInfo event handler declarations

////@begin wxPageInfo member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxPageInfo member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxPageInfo member variables
    wxStaticText* txtMessage;
////@end wxPageInfo member variables

	void SetMessage(const char *msg);
protected:
};


inline
void wxPageInfo::SetMessage(const char *msg) { 
	txtMessage->SetLabel(wxT(msg));
}
}

}
#endif
    // _WXPAGEINFO_H_
