/////////////////////////////////////////////////////////////////////////////
// Name:        wxpagelocicreation.h
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Wed 05 Dec 2007 04:14:03 PM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Wed 05 Dec 2007 04:14:03 PM CST

#ifndef _WXPAGELOCICREATION_H_
#define _WXPAGELOCICREATION_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "wxpagelocicreation.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/choicebk.h"
#include "wx/toolbar.h"
////@end includes

#include "locusmanager.h"
#include "wxchromcfgdialog.h"

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxChoicebook;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_PAGE_LOCI_CREATION 10038
#define ID_CHOICEBOOK1 10058
#define ID_TOOLBAR1 10136
#define ID_CMD_DELETE_CHROM 10009
#define ID_CMD_ADD_CHROM 10006
#define ID_CMD_LOAD_CHROM 10003
#define SYMBOL_WXPAGELOCICREATION_STYLE 0
#define SYMBOL_WXPAGELOCICREATION_TITLE _("Loci Creation")
#define SYMBOL_WXPAGELOCICREATION_IDNAME ID_PAGE_LOCI_CREATION
#define SYMBOL_WXPAGELOCICREATION_SIZE wxSize(800, 600)
#define SYMBOL_WXPAGELOCICREATION_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

#include "appinterface.h"

namespace GenomeSIM {

namespace GUI {
/*!
 * wxPageLociCreation class declaration
 */

class wxPageLociCreation: public wxPanel, public AppInterface {    
    DECLARE_DYNAMIC_CLASS( wxPageLociCreation )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxPageLociCreation( );
    wxPageLociCreation( wxWindow* parent, wxWindowID id = SYMBOL_WXPAGELOCICREATION_IDNAME, const wxPoint& pos = SYMBOL_WXPAGELOCICREATION_POSITION, const wxSize& size = SYMBOL_WXPAGELOCICREATION_SIZE, long style = SYMBOL_WXPAGELOCICREATION_STYLE );

	~wxPageLociCreation();

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXPAGELOCICREATION_IDNAME, const wxPoint& pos = SYMBOL_WXPAGELOCICREATION_POSITION, const wxSize& size = SYMBOL_WXPAGELOCICREATION_SIZE, long style = SYMBOL_WXPAGELOCICREATION_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxPageLociCreation event handler declarations

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_CMD_DELETE_CHROM
    void OnCmdDeleteChromClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_CMD_ADD_CHROM
    void OnCmdAddChromClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_CMD_LOAD_CHROM
    void OnCmdLoadChromClick( wxCommandEvent& event );

////@end wxPageLociCreation event handler declarations

////@begin wxPageLociCreation member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxPageLociCreation member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxPageLociCreation member variables
    wxChoicebook* nbChromDisplay;
////@end wxPageLociCreation member variables

	void SetChromosomes(vector<FileBasedChromosome *> *ch) { chromosomes=ch; }


	void InitAppController(AppController *);

	/**
	 * @brief This is called prior to saving the configuration
	 */
	void Commit();

	/**
	 * @brief This is called just after a configuration has been loaded
	 */
	void RefreshSettings();

	bool HasChanged();


	bool VerifyForRun();

protected:
	bool hasChanged;
	void AddMessageBox(const char *msg);

	uint chromosomeCount;

	vector<FileBasedChromosome *> *chromosomes;

	ChromPool::BlockDefinition *defaultBlock;
	
	/**
	 * Keep up with the various pages. The wx functions return a wrapper which interferes with reaching the base class
	 */
	vector<wxChromCfgDialog *> chromPages;
};

}

}

#endif
    // _WXPAGELOCICREATION_H_
