/////////////////////////////////////////////////////////////////////////////
// Name:        wxpagebbchrom.h
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Thu 06 Dec 2007 01:21:37 PM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Thu 06 Dec 2007 01:21:37 PM CST

#ifndef _WXPAGEBBCHROM_H_
#define _WXPAGEBBCHROM_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "wxpagebbchrom.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/grid.h"
#include "wx/spinctrl.h"
#include "wx/toolbar.h"
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
class wxGrid;
class wxSpinCtrl;
////@end forward declarations
#include "wxchromcfgdialog.h"
#include "simulation/chrompool.h"
/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10039
#define ID_CHROM_LABEL 10003
#define ID_GRID_BLOCKS 10005
#define ID_BLOCK_COUNTS 10133
#define ID_GAUGE_COMPLETION 10042
#define ID_ADD_BLOCK 10002
#define ID_REMOVE_BLOCK 10006
#define SYMBOL_WXPAGEBBCHROM_STYLE wxRESIZE_BORDER
#define SYMBOL_WXPAGEBBCHROM_TITLE _("Block Based Chromosome")
#define SYMBOL_WXPAGEBBCHROM_IDNAME ID_DIALOG
#define SYMBOL_WXPAGEBBCHROM_SIZE wxSize(400, 300)
#define SYMBOL_WXPAGEBBCHROM_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif

namespace GenomeSIM {

namespace GUI {

using namespace Simulation;


/*!
 * wxPageBBChrom class declaration
 */

class wxPageBBChrom: public wxPanel, public wxChromCfgDialog 	{    
    DECLARE_DYNAMIC_CLASS( wxPageBBChrom )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    wxPageBBChrom( );
    wxPageBBChrom( wxWindow* parent, wxWindowID id = SYMBOL_WXPAGEBBCHROM_IDNAME, const wxPoint& pos = SYMBOL_WXPAGEBBCHROM_POSITION, const wxSize& size = SYMBOL_WXPAGEBBCHROM_SIZE, long style = SYMBOL_WXPAGEBBCHROM_STYLE );


	~wxPageBBChrom() { }
    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_WXPAGEBBCHROM_IDNAME, const wxPoint& pos = SYMBOL_WXPAGEBBCHROM_POSITION, const wxSize& size = SYMBOL_WXPAGEBBCHROM_SIZE, long style = SYMBOL_WXPAGEBBCHROM_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin wxPageBBChrom event handler declarations

    /// wxEVT_SIZE event handler for ID_DIALOG
    void OnSize( wxSizeEvent& event );

    /// wxEVT_COMMAND_TEXT_UPDATED event handler for ID_CHROM_LABEL
    void OnChromLabelUpdated( wxCommandEvent& event );

    /// wxEVT_GRID_CELL_CHANGE event handler for ID_GRID_BLOCKS
    void OnCellChange( wxGridEvent& event );

    /// wxEVT_GRID_EDITOR_HIDDEN event handler for ID_GRID_BLOCKS
    void OnEditorHidden( wxGridEvent& event );

    /// wxEVT_GRID_CMD_EDITOR_HIDDEN event handler for ID_GRID_BLOCKS
    void OnGridBlocksEditorHidden( wxGridEvent& event );

    /// wxEVT_COMMAND_SPINCTRL_UPDATED event handler for ID_BLOCK_COUNTS
    void OnBlockCountsUpdated( wxSpinEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_ADD_BLOCK
    void OnAddBlockClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_MENU_SELECTED event handler for ID_REMOVE_BLOCK
    void OnRemoveBlockClick( wxCommandEvent& event );

////@end wxPageBBChrom event handler declarations

////@begin wxPageBBChrom member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end wxPageBBChrom member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin wxPageBBChrom member variables
    wxTextCtrl* txtChromLabel;
    wxGrid* gridBlocks;
    wxSpinCtrl* rangeBlockCounts;
    wxGauge* guageCompletion;
    wxStaticText* txtPercentComplete;
////@end wxPageBBChrom member variables

	void InitLabel(const char *label, uint chromID);
	void InitList();
	void RefreshSize();
	void AddNewBlock();
	void UpdateCompletionMonitor();
	void DeleteRow(int row, int count);

	void AddBlock(ChromPool::BlockDefinition &block);

	void SetLabel(const char *label);

	uint GetBlockCount() { return gridBlocks->GetNumberRows(); }

	void Commit();

	void RefreshSettings() {}
	Simulation::ChromPool pool;

	void WriteMarkerInfo(const char *filename);	

	vector<Locus> RealizeChromosome(ChromPool::BlockDefinition& block);
};

}

}

#endif
    // _WXPAGEBBCHROM_H_
