/////////////////////////////////////////////////////////////////////////////
// Name:        dlggrowthreview.h
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Tue 04 Dec 2007 04:51:43 PM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 04 Dec 2007 04:51:43 PM CST

#ifndef _DLGGROWTHREVIEW_H_
#define _DLGGROWTHREVIEW_H_

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma interface "dlggrowthreview.cpp"
#endif

/*!
 * Includes
 */

////@begin includes
#include "wx/html/htmlwin.h"
////@end includes
#include <string>
/*!
 * Forward declarations
 */

////@begin forward declarations
class wxHtmlWindow;
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10033
#define ID_HTMLWINDOW 10034
#define SYMBOL_DLGGROWTHREVIEW_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_DLGGROWTHREVIEW_TITLE _("Growth Chart Review")
#define SYMBOL_DLGGROWTHREVIEW_IDNAME ID_DIALOG
#define SYMBOL_DLGGROWTHREVIEW_SIZE wxSize(800, 600)
#define SYMBOL_DLGGROWTHREVIEW_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif
#ifndef wxFIXED_MINSIZE
#define wxFIXED_MINSIZE 0
#endif
namespace GenomeSIM  {
namespace GUI {

using namespace std;
/*!
 * DlgGrowthReview class declaration
 */

class DlgGrowthReview: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( DlgGrowthReview )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    DlgGrowthReview( );
    DlgGrowthReview( wxWindow* parent, wxWindowID id = SYMBOL_DLGGROWTHREVIEW_IDNAME, const wxString& caption = SYMBOL_DLGGROWTHREVIEW_TITLE, const wxPoint& pos = SYMBOL_DLGGROWTHREVIEW_POSITION, const wxSize& size = SYMBOL_DLGGROWTHREVIEW_SIZE, long style = SYMBOL_DLGGROWTHREVIEW_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_DLGGROWTHREVIEW_IDNAME, const wxString& caption = SYMBOL_DLGGROWTHREVIEW_TITLE, const wxPoint& pos = SYMBOL_DLGGROWTHREVIEW_POSITION, const wxSize& size = SYMBOL_DLGGROWTHREVIEW_SIZE, long style = SYMBOL_DLGGROWTHREVIEW_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin DlgGrowthReview event handler declarations

    /// wxEVT_UPDATE_UI event handler for ID_HTMLWINDOW
    void OnHtmlwindowUpdate( wxUpdateUIEvent& event );

////@end DlgGrowthReview event handler declarations

////@begin DlgGrowthReview member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end DlgGrowthReview member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();


	void SetFilename(const char *filename);
////@begin DlgGrowthReview member variables
    wxHtmlWindow* htmlGrowthReport;
////@end DlgGrowthReview member variables
protected:
	string filename;
	bool refreshImage;
};

}
}

#endif
    // _DLGGROWTHREVIEW_H_
