/////////////////////////////////////////////////////////////////////////////
// Name:        dlggrowthreview.cpp
// Purpose:     
// Author:      Eric Torstenson
// Modified by: 
// Created:     Tue 04 Dec 2007 04:51:43 PM CST
// RCS-ID:      
// Copyright:   Copyright 2007 Ritchie Lab - See COPYING for License 
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), Tue 04 Dec 2007 04:51:43 PM CST

#if defined(__GNUG__) && !defined(__APPLE__)
#pragma implementation "dlggrowthreview.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "dlggrowthreview.h"

////@begin XPM images
////@end XPM images
namespace GenomeSIM  {
namespace GUI {

/*!
 * DlgGrowthReview type definition
 */

IMPLEMENT_DYNAMIC_CLASS( DlgGrowthReview, wxDialog )

/*!
 * DlgGrowthReview event table definition
 */

BEGIN_EVENT_TABLE( DlgGrowthReview, wxDialog )

////@begin DlgGrowthReview event table entries
    EVT_UPDATE_UI( ID_HTMLWINDOW, DlgGrowthReview::OnHtmlwindowUpdate )

////@end DlgGrowthReview event table entries

END_EVENT_TABLE()

/*!
 * DlgGrowthReview constructors
 */

DlgGrowthReview::DlgGrowthReview( ) : refreshImage(true)	{
}

DlgGrowthReview::DlgGrowthReview( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style ) : refreshImage(true)  {
    Create(parent, id, caption, pos, size, style);
}

/*!
 * DlgGrowthReview creator
 */

bool DlgGrowthReview::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin DlgGrowthReview member initialisation
    htmlGrowthReport = NULL;
////@end DlgGrowthReview member initialisation

////@begin DlgGrowthReview creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end DlgGrowthReview creation
    return TRUE;
}

/*!
 * Control creation for DlgGrowthReview
 */

void DlgGrowthReview::CreateControls()
{    
////@begin DlgGrowthReview content construction
    DlgGrowthReview* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    htmlGrowthReport = new wxHtmlWindow( itemDialog1, ID_HTMLWINDOW, wxDefaultPosition, wxSize(600, 480), wxHW_SCROLLBAR_AUTO|wxSUNKEN_BORDER|wxHSCROLL|wxVSCROLL );
    itemBoxSizer2->Add(htmlGrowthReport, 1, wxGROW|wxALL, 5);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer4, 0, wxALIGN_RIGHT|wxALL, 5);

    wxButton* itemButton5 = new wxButton( itemDialog1, wxID_OK, _("OK"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton5, 0, wxALIGN_BOTTOM|wxALL, 5);

////@end DlgGrowthReview content construction
}

/*!
 * Should we show tooltips?
 */

bool DlgGrowthReview::ShowToolTips()
{
    return TRUE;
}

/*!
 * Get bitmap resources
 */

wxBitmap DlgGrowthReview::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin DlgGrowthReview bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end DlgGrowthReview bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon DlgGrowthReview::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin DlgGrowthReview icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end DlgGrowthReview icon retrieval
}

/*!
 * wxEVT_UPDATE_UI event handler for ID_HTMLWINDOW
 */

void DlgGrowthReview::OnHtmlwindowUpdate( wxUpdateUIEvent& event )
{
	if (refreshImage) {
		wxString filename = wxT(this->filename.c_str());
		htmlGrowthReport->LoadFile(filename);
		refreshImage = false;			 
	}

////@begin wxEVT_UPDATE_UI event handler for ID_HTMLWINDOW in DlgGrowthReview.
    // Before editing this code, remove the block markers.
    event.Skip();
////@end wxEVT_UPDATE_UI event handler for ID_HTMLWINDOW in DlgGrowthReview. 
}



void DlgGrowthReview::SetFilename( const char *filename) {
	this->filename=filename;
	refreshImage = true;
}




}
}



